name: Build and deploy pyfs
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: Test
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pysvn
        run: sudo apt-get install python3-pysvn
      - name: Setup
        run: python3 -m pip install oc_pyfs && python3 -m unittest discover -v && python3 setup.py bdist_wheel
