name: Build and deploy pyfs
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: Test
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install setuptools
        run: python3 -m pip install --upgrade pip setuptools wheel
      - name: Install pysvn
        run: sudo apt-get install python3-pysvn
      - name: Setup
        run: sudo python3 -m pip install ./ && python3 -m unittest discover -v && sudo python3 setup.py bdist_wheel
