name: On Release, deploying to Prod
on:
  release:
    types: [published]
jobs:
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-py3-pysvn-build-deploy.yml@add-common-wf
    with:
      process_env: Prod
    secrets: inherit